global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["IP:9100"]
  - job_name: node-exporter
    static_configs:
      - targets: ["IP:9100"]
  - job_name: node-ipfs
    metrics_path: "debug/metrics/prometheus"
    static_configs:
      - targets: ["IP:5001"]

