global:
  scrape_interval: 15s # Interval waktu antara setiap scraping
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['IP:9100']  #port prometheus
scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['IP:9100'] 
scrape_configs:
  - job_name: node-ipfs
    static_configs:
      - targets: ['IP:5001'] 
